#!/usr/bin/env bash

echo "Installation de Docker"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
echo "fingerprint : 9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88"
sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

sudo apt-get -y update

sudo apt-get -y install docker-ce docker-ce-cli containerd.io

echo "Vérification Docker"
sudo docker run hello-world

sudo groupadd docker
sudo usermod -aG docker $USER

sudo systemctl enable docker

echo "**** Il faudra redémarrer votre machine à la fin de l'installation !!! ****"

sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
docker-compose --version
