#!/usr/bin/env bash

user=eliberty
path_authorized_keys=/home/${user}/.ssh/authorized_keys
keyssh="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqsF9iqWQFj+P27EY86TgHw91SIhDIzS6C1+7nPYTRGMXPx5i/FCdmZqq1bmDBLEzTHgUwL9i4eYFs5Xq6GU8Jr55BgQuQ7FWpGPxgJ61Aapm++bcBObloa3ROh1Kxy95Qz+ApUqfp5Eie8ZIl3eGBpAVsboMq1OwHTOPYRLNcs2r8Ac+wUUnzTRmm/WV2S2t3pU/2Zx9FYZ/i45xYsux0swlb6iGhA6uuG4WC7D3kyEk/Z1gxDUlAcekC48mjZ3vf0tbBP8B0D3NXeTpJ7GuTRW31Qaq4eLR54bQ9tMfsbXJtuRxbsOteKKr4AjONd8hXLXBhmKk/g071z26zHBwc2OF3yhq++OBLsBNxBcOppVZ85BkmOtRDN0y5QYEjdgV3C/Lq3eeHiVYwKy6npIc/ah7ztoPEcbqpZODp3359UH4DLVkgkUHNqzVYXbru/vYZhfRjK/XZcy4Sd93QKszYz76ztC8Y0mg80U9tbhEQ38IdwhrZQPvrq5uvlLU3c4+xgTpvdZQFboorJ8gFtSwlXB0o1y+iT6YAW03PIJuAmjVVA34hTue1XpTNoz1gPomceRd42gJHtSAVQQIG0Pg66G3ons4EV0j/v9A8XfdTHOblkEFvegAdFiMWF7zmPtPxrMxmriRWLwE2A9N/N830Bko8jL+Ah5+y31pl1yLRmQ== richard@rbeliberty"

sudo apt-get install -y build-essential libpq-dev
sudo apt-get install -y -q jq curl openssh-server

useradd ${user} --uid 1010 --create-home
sudo adduser ${user} sudo
#sudo passwd ${user}
mkdir -p /home/${user}/.ssh/
touch /home/${user}/.ssh/authorized_keys
echo $keyssh >> $path_authorized_keys
chown -R ${user}:${user} /home/eliberty
# shellcheck disable=SC2024
sudo echo '${user} ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers