#!/usr/bin/env bash

sudo apt-get install -y build-essential libpq-dev
sudo apt-get install -y -q jq curl
sudo apt-get install -y -q git python3-pip libssl-dev libffi-dev python3 python3-dev

sudo pip3 install ansible==2.8 futures python-dateutil awscli boto3 psycopg2
sudo pip3 install ansible-modules-hashivault

