#!/usr/bin/env bash

echo "Installation de ZSH"
sudo apt-get -y install powerline fonts-powerline zsh-theme-powerlevel9k zsh-syntax-highlighting
sudo curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sudo sh
sudo chsh -s /usr/bin/zsh
sudo usermod -s /usr/bin/zsh $(whoami)

echo "source /usr/share/powerlevel9k/powerlevel9k.zsh-theme" >> ~/.zshrc
echo "source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc